encoding: UTF-8

theme: jekyll-theme-hacker
# ---
title: yetamine.net
description: Happy coding!
# ---
google_analytics:
show_downloads: false

github: # GitHub configuration override
  repository_url: http://github.com/yetamine/
