encoding: UTF-8

theme: jekyll-theme-hacker
plugins:
  - jekyll-redirect-from
# ---
title: yetamine.net
logo: /assets/images/logo.png
description: Happy coding!
# ---
google_analytics:
show_downloads: false

github: # GitHub configuration override
  repository_url: http://github.com/yetamine/
